import { createHash } from 'node:crypto';
import { performance } from 'node:perf_hooks';
import {
  RULE_LIMITS,
  RuleReview,
  RuleSystemKind,
  emptyRuleColumns,
  ruleBookManifestSchema,
  ruleNodeSchema,
  ruleSlugSchema,
  validateRuleContent,
  type RuleBookManifest,
  type RuleColumns,
  type RuleNode,
  type RulePageSpan,
} from './rules.js';

export type RuleUpload = { name: string; bytes: Buffer };
export type ParsedRuleBook = {
  manifest: RuleBookManifest;
  columns: RuleColumns;
  inputHash: string;
  nodeCount: number;
};
function invalid(file: string, line: number, message: string): never {
  throw new Error(`${file}:${line}: ${message}`);
}
function decode(file: RuleUpload): string {
  try {
    return new TextDecoder('utf-8', { fatal: true }).decode(file.bytes).replace(/\r\n?/g, '\n');
  } catch {
    return invalid(file.name, 1, 'Invalid UTF-8');
  }
}
function pages(value: string, pageCount: number, file: string, line: number): number[] {
  if (value === '-') return [];
  const match = /^(\d+)(?:-(\d+))?$/.exec(value);
  if (!match) invalid(file, line, 'Invalid PDF page range');
  const first = Number(match[1]);
  const last = Number(match[2] ?? match[1]);
  if (first < 1 || last < first || last > pageCount)
    invalid(file, line, 'PDF page exceeds source bounds');
  return Array.from({ length: last - first + 1 }, (_, index) => first + index);
}
function printed(value: string): string[] {
  return value === '-' ? [] : [value];
}
export function parseRuleBook(files: RuleUpload[]): ParsedRuleBook {
  const deadline = performance.now() + RULE_LIMITS.validationDeadlineMs;
  if (!files.length || files.length > RULE_LIMITS.importFiles)
    throw new Error('Import file count exceeded');
  const byName = new Map<string, RuleUpload>();
  let totalBytes = 0;
  for (const file of files) {
    if (!/^(manifest\.json|[a-z_]+\.md)$/.test(file.name) || byName.has(file.name))
      invalid(file.name, 1, 'Unsafe or duplicate upload filename');
    if (file.bytes.byteLength > RULE_LIMITS.importFileBytes)
      invalid(file.name, 1, 'File byte limit exceeded');
    totalBytes += file.bytes.byteLength;
    byName.set(file.name, file);
  }
  if (totalBytes > RULE_LIMITS.importBytes) throw new Error('Combined import byte limit exceeded');
  const manifestFile = byName.get('manifest.json');
  if (!manifestFile) throw new Error('manifest.json:1: Missing manifest');
  const manifest = ruleBookManifestSchema.parse(JSON.parse(decode(manifestFile)));
  if (byName.size !== manifest.columns.length + 1)
    throw new Error('Manifest must list exactly the uploaded column files');
  const columns = emptyRuleColumns();
  const targets = new Map<string, RuleNode>();
  let nodeCount = 0;
  for (const column of manifest.columns) {
    const file = byName.get(column.file);
    if (!file) invalid(column.file, 1, 'Missing column file');
    if (createHash('sha256').update(file.bytes).digest('hex') !== column.hash)
      invalid(file.name, 1, 'Column hash mismatch');
    const lines = decode(file).split(/(?<=\n)/);
    const root: RuleNode = {
      name: manifest.source.title,
      source: manifest.source.slug,
      aliases: [],
      text: '',
      review: RuleReview.Extracted,
      pdfPages: [],
      printedPages: [],
      children: {},
      structural: true,
    };
    columns[column.column][manifest.source.slug] = root;
    let current: RuleNode | null = null;
    let titlePending = true;
    let splitterTitle: string | null = null;
    let currentBytes = 0;
    let header = false;
    let fence: { char: string; length: number } | null = null;
    let activePage: { pdfPage: number | null; printedPage: string | null } | null = null;
    for (let index = 0; index < lines.length; index++) {
      if (performance.now() > deadline)
        invalid(file.name, index + 1, 'Validation deadline exceeded');
      const line = lines[index]!;
      const trimmed = line.trim();
      const fenceMatch = /^\s{0,3}(`{3,}|~{3,})/.exec(line);
      const outsideFence = fence === null;
      if (outsideFence && trimmed.startsWith('<!-- column:')) {
        if (header || current)
          invalid(file.name, index + 1, 'Duplicate or misplaced column header');
        const match =
          /^<!-- column:\s*([a-z_]+)\s*\|\s*source:\s*([a-z0-9_-]+)(\s*\|[^<>]*)?\s*-->$/.exec(
            trimmed
          );
        if (!match || match[1] !== column.column || match[2] !== manifest.source.slug)
          invalid(file.name, index + 1, 'Column/source header mismatch');
        for (const metadata of (match[3] ?? '').split('|').filter((value) => value.trim())) {
          if (
            metadata.trim() !==
              'generated by split_by_outline.py from the outline; do not edit by hand' &&
            !/^\s*(title|edition|publication|converter|version|marker-format|nodes|pages):\s*[^<>\r\n]{1,200}\s*$/.test(
              metadata
            )
          )
            invalid(file.name, index + 1, 'Unknown column-header control metadata');
        }
        header = true;
        continue;
      }
      if (outsideFence && trimmed.startsWith('<!-- node:')) {
        if (!header) invalid(file.name, index + 1, 'Missing column header');
        const match =
          /^<!-- node:\s*([a-z0-9_.-]+)\s*\|\s*pages:\s*([^|]+?)\s*\|\s*printed:\s*([^|]+?)\s*-->$/.exec(
            trimmed
          );
        if (!match) invalid(file.name, index + 1, 'Malformed node marker');
        const segments = match[1]!.split('.');
        if (segments.length > RULE_LIMITS.contentDepth)
          invalid(file.name, index + 1, 'Content depth exceeded');
        for (const segment of segments)
          if (!ruleSlugSchema.safeParse(segment).success)
            invalid(file.name, index + 1, 'Unsafe node path');
        const target = `${column.column}.${match[1]}`;
        if (targets.has(target)) invalid(file.name, index + 1, 'Duplicate node marker');
        let parent = root;
        for (const segment of segments.slice(0, -1)) {
          if (!Object.hasOwn(parent.children, segment))
            invalid(file.name, index + 1, 'Missing parent node');
          parent = parent.children[segment]!;
        }
        current = {
          name: splitterTitle ?? segments.at(-1)!,
          aliases: [],
          source: manifest.source.slug,
          text: '',
          review: RuleReview.Extracted,
          pdfPages: pages(match[2]!.trim(), manifest.source.pageCount, file.name, index + 1),
          printedPages: printed(match[3]!.trim()),
          children: {},
        };
        parent.children[segments.at(-1)!] = current;
        targets.set(target, current);
        titlePending = splitterTitle === null;
        splitterTitle = null;
        currentBytes = 0;
        activePage = null;
        if (++nodeCount > RULE_LIMITS.nodes) invalid(file.name, index + 1, 'Node count exceeded');
        continue;
      }
      if (outsideFence && trimmed.startsWith('<!-- page ')) {
        if (!current) invalid(file.name, index + 1, 'Page marker outside node');
        const match = /^<!-- page (\d+|-)(?: \(printed ([^()]+)\))? -->$/.exec(trimmed);
        if (!match) invalid(file.name, index + 1, 'Malformed inline page marker');
        const pdfPage = match[1] === '-' ? null : Number(match[1]);
        if (
          pdfPage !== null &&
          (!Number.isInteger(pdfPage) || pdfPage < 1 || pdfPage > manifest.source.pageCount)
        )
          invalid(file.name, index + 1, 'Inline page exceeds source bounds');
        activePage = { pdfPage, printedPage: !match[2] || match[2] === '-' ? null : match[2] };
        continue;
      }
      const splitterHeading = outsideFence && /^#{1,6}\s+(.+?)\s*#*\s*$/.exec(trimmed);
      if (splitterHeading && lines[index + 1]?.trim().startsWith('<!-- node:')) {
        if (!header) invalid(file.name, index + 1, 'Missing column header');
        splitterTitle = splitterHeading[1]!;
        continue;
      }
      if (!current) {
        if (trimmed) invalid(file.name, index + 1, 'Unassigned original body text');
        continue;
      }
      const start = current.text.length;
      current.text += line;
      currentBytes += Buffer.byteLength(line, 'utf8');
      if (currentBytes > RULE_LIMITS.textBytes)
        invalid(file.name, index + 1, 'Node text byte limit exceeded');
      if (activePage && line.length) {
        current.pageSpans ??= [];
        const previous = current.pageSpans.at(-1);
        if (
          previous &&
          previous.end === start &&
          previous.pdfPage === activePage.pdfPage &&
          previous.printedPage === activePage.printedPage
        )
          previous.end = current.text.length;
        else
          current.pageSpans.push({
            start,
            end: current.text.length,
            ...activePage,
          } satisfies RulePageSpan);
      }
      const heading = /^#{1,6}\s+(.+?)\s*#*\s*$/.exec(trimmed);
      if (heading && titlePending && outsideFence) {
        current.name = heading[1]!;
        titlePending = false;
      }
      if (fenceMatch) {
        const marker = fenceMatch[1]!;
        if (!fence) fence = { char: marker[0]!, length: marker.length };
        else if (
          marker[0] === fence.char &&
          marker.length >= fence.length &&
          new RegExp(`^\\s{0,3}${fence.char}{${fence.length},}\\s*$`).test(line)
        )
          fence = null;
      }
    }
    if (!header) invalid(file.name, 1, 'Missing column header');
  }
  for (const [path, enrichment] of Object.entries(manifest.enrichment ?? {})) {
    const target = targets.get(path);
    if (!target) throw new Error(`manifest.json:1: Enrichment path does not exist: ${path}`);
    Object.assign(target, enrichment);
  }
  for (const target of targets.values()) {
    if (!target.text.trim().length) {
      target.structural = true;
      target.text = '';
    }
    ruleNodeSchema.parse(target);
  }
  validateRuleContent(
    { ...columns, instructions: '', sources: [manifest.source], mapping: {} },
    RuleSystemKind.Library
  );
  const inputHash = createHash('sha256');
  for (const file of [...files].sort((a, b) => a.name.localeCompare(b.name)))
    inputHash.update(file.name).update('\0').update(file.bytes).update('\0');
  return { manifest, columns, inputHash: inputHash.digest('hex'), nodeCount };
}
