export const SETTINGS_CONTRACT_VERSION = 1;
export const GM_RESPONSE_SCHEMA_VERSION = 1;
export const DICE_GAMEPLAY_RESPONSE_SCHEMA_VERSION = 2;
export const LEGACY_ARCHIVE_FORMAT_VERSION = 1;
export const DICE_ARCHIVE_FORMAT_VERSION = 2;
export const ARCHIVE_FORMAT_ID = 'local-rpg';
export const ARCHIVE_FORMAT_VERSION = DICE_ARCHIVE_FORMAT_VERSION;
