export const SETTINGS_CONTRACT_VERSION = 1;
export const GM_RESPONSE_SCHEMA_VERSION = 1;
export const DICE_GAMEPLAY_RESPONSE_SCHEMA_VERSION = 2;
export const LEGACY_ARCHIVE_FORMAT_VERSION = 1;
export const DICE_ARCHIVE_FORMAT_VERSION = 2;
export const RULE_BOOK_PACKAGE_VERSION = 1;
export const RULE_BACKUP_FORMAT_VERSION = 1;
export const RULE_GAMEPLAY_RESPONSE_SCHEMA_VERSION = 3;
export const RULE_ARCHIVE_FORMAT_VERSION = 3;
export const ARCHIVE_FORMAT_ID = 'local-rpg';

export const KNOWLEDGE_GAMEPLAY_RESPONSE_SCHEMA_VERSION = 4;
export const KNOWLEDGE_ARCHIVE_FORMAT_VERSION = 4;
export const ENABLED_GAMEPLAY_RESPONSE_SCHEMA_VERSION: number =
  KNOWLEDGE_GAMEPLAY_RESPONSE_SCHEMA_VERSION;
export const LEGACY_GAMEPLAY_DIGEST_VERSION = 1;
export const KNOWLEDGE_GAMEPLAY_DIGEST_VERSION = 2;

export const ARCHIVE_FORMAT_VERSION = KNOWLEDGE_ARCHIVE_FORMAT_VERSION;
