import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { appRoot } from '../src/config.js';
import { parseRuleBook } from '../src/domain/ruleImport.js';

test('manifest preparation accepts original columns without editing them and refuses overwritten/in-place outputs', async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'rpg-manifest-test-'));
  const columns = path.join(directory, 'columns');
  const original = Buffer.from(
    '<!-- column: core_rules | source: original-fixture | generated by split_by_outline.py from the outline; do not edit by hand -->\n# Original title\n<!-- node: rule | pages: 1 | printed: - -->\nOriginal synthetic body.\n'
  );
  try {
    await mkdir(columns);
    await writeFile(path.join(columns, 'core_rules.md'), original);
    const output = path.join(directory, 'manifest.json');
    const args = [
      '--import',
      'tsx',
      'scripts/prepare-rule-manifest.mjs',
      '--columns',
      columns,
      '--title',
      'Original fixture',
      '--page-count',
      '2',
      '--out',
    ];
    const root = path.resolve(appRoot, '..');
    await promisify(execFile)(process.execPath, [...args, output], {
      cwd: root,
      windowsHide: true,
    });
    const manifest = await readFile(output);
    const parsed = parseRuleBook([
      { name: 'manifest.json', bytes: manifest },
      { name: 'core_rules.md', bytes: original },
    ]);
    assert.equal(parsed.nodeCount, 1);
    assert.equal(manifest.toString().includes('Original synthetic body.'), false);
    assert.deepEqual(await readFile(path.join(columns, 'core_rules.md')), original);
    await assert.rejects(
      promisify(execFile)(process.execPath, [...args, output], { cwd: root, windowsHide: true }),
      /EEXIST/
    );
    await assert.rejects(
      promisify(execFile)(process.execPath, [...args, path.join(columns, 'manifest.json')], {
        cwd: root,
        windowsHide: true,
      }),
      /outside the read-only column directory/
    );
    await writeFile(path.join(columns, 'unknown.md'), 'Original unrelated file');
    await assert.rejects(
      promisify(execFile)(process.execPath, [...args, path.join(directory, 'other.json')], {
        cwd: root,
        windowsHide: true,
      }),
      /unknown Markdown filename/
    );
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});
