import { test } from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { readFile, stat } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { parseRuleBook, type RuleUpload } from '../src/domain/ruleImport.js';
import { RULE_COLUMNS, type RuleNode } from '../src/domain/rules.js';
import { appRoot } from '../src/config.js';

const enabled = process.env.NODE_ENV === 'test' && !!process.env.RPG_RULES_HANDOFF_COLUMNS;
test(
  'opt-in private handoff validation reads original columns without editing/copying them and proves body/UTF-16 contract',
  { skip: !enabled },
  async () => {
    const directory = path.resolve(process.env.RPG_RULES_HANDOFF_COLUMNS!);
    const publicRoot = path.resolve(appRoot, '..') + path.sep;
    assert.equal(
      directory.startsWith(publicRoot),
      false,
      'Private handoff artifacts must stay outside the public repository'
    );
    const files: RuleUpload[] = [];
    const hashes = new Map<string, string>();
    const originalBodies = new Map<string, string[]>();
    let source = '';
    let markerCount = 0;
    for (const column of RULE_COLUMNS) {
      const filename = `${column}.md`;
      assert.ok((await stat(path.join(directory, filename))).size <= 10 * 1024 * 1024);
      const bytes = await readFile(path.join(directory, filename));
      const text = new TextDecoder('utf8', { fatal: true }).decode(bytes).replace(/\r\n?/g, '\n');
      const header =
        /^<!-- column: ([a-z_]+) \| source: ([a-z0-9_-]+) \| generated by split_by_outline.py from the outline; do not edit by hand -->/.exec(
          text
        );
      assert.ok(header, 'Observed splitter header is required for this handoff check');
      assert.equal(header[1], column);
      if (!source) source = header[2]!;
      assert.equal(header[2], source);
      hashes.set(filename, createHash('sha256').update(bytes).digest('hex'));
      files.push({ name: filename, bytes });
      const lines = text.split('\n');
      markerCount += lines.filter((line) => line.startsWith('<!-- node:')).length;
      // The owner emits its navigation heading immediately before each node marker.
      // Compare literal nonempty source-body lines against direct node text, independently of node names.
      originalBodies.set(
        column,
        lines.filter(
          (line, index) =>
            line.trim() &&
            !/^<!-- (column:|node:|page )/.test(line.trim()) &&
            !(/^#{1,6} /.test(line) && lines[index + 1]?.startsWith('<!-- node:'))
        )
      );
    }
    const manifest = {
      format: 'rules-book',
      version: 1,
      markerFormatVersion: 1,
      source: {
        slug: source,
        title: process.env.RPG_RULES_HANDOFF_TITLE ?? 'Private read-only handoff',
        pageCount: Number(process.env.RPG_RULES_HANDOFF_PAGE_COUNT),
        pdfHash: null,
      },
      columns: RULE_COLUMNS.map((column) => ({
        column,
        file: `${column}.md`,
        hash: hashes.get(`${column}.md`),
      })),
      converter: { id: 'split_by_outline', version: 'observed-v1' },
      coverage: {
        description: 'Read-only column contract validation; extraction audit remains separate',
        omissions: ['PDF/image/OCR completeness is not certified by this contract check'],
      },
    };
    const uploads = [
      { name: 'manifest.json', bytes: Buffer.from(JSON.stringify(manifest)) },
      ...files,
    ];
    const parsed = parseRuleBook(uploads);
    assert.equal(parsed.nodeCount, markerCount);
    if (process.env.RPG_RULES_HANDOFF_EXPECTED_NODES)
      assert.equal(parsed.nodeCount, Number(process.env.RPG_RULES_HANDOFF_EXPECTED_NODES));
    let directLines = 0;
    let sampled: { path: string; node: RuleNode } | undefined;
    for (const column of RULE_COLUMNS) {
      const body: string[] = [];
      function visit(node: RuleNode, relative: string) {
        body.push(...node.text.split('\n').filter((line) => line.trim()));
        if (!sampled && !node.structural && node.text.trim())
          sampled = { path: `${column}.${relative}`, node };
        for (const [key, child] of Object.entries(node.children))
          visit(child, relative ? `${relative}.${key}` : key);
      }
      for (const [key, node] of Object.entries(parsed.columns[column][source]!.children))
        visit(node, key);
      const original = originalBodies.get(column)!;
      assert.equal(body.length, original.length, 'All original body lines must be retained');
      // Failure output must never print private original body text.
      assert.equal(
        createHash('sha256').update(JSON.stringify(body)).digest('hex'),
        createHash('sha256').update(JSON.stringify(original)).digest('hex'),
        'Original body lines must remain byte-identical after normalization'
      );
      directLines += body.length;
    }
    assert.ok(sampled);
    const start = sampled.node.text.search(/\S/);
    const quote = sampled.node.text.slice(start, start + 8);
    const enriched = {
      ...manifest,
      enrichment: {
        [sampled.path]: {
          fields: { handoff_probe: 'original' },
          fieldEvidence: {
            handoff_probe: { kind: 'text', quote, start, end: start + quote.length },
          },
        },
      },
    };
    assert.equal(
      parseRuleBook([
        { name: 'manifest.json', bytes: Buffer.from(JSON.stringify(enriched)) },
        ...files,
      ]).nodeCount,
      parsed.nodeCount
    );
    for (const file of files)
      assert.equal(
        createHash('sha256')
          .update(await readFile(path.join(directory, file.name)))
          .digest('hex'),
        hashes.get(file.name),
        'Read-only handoff files must remain byte-identical'
      );
    console.log(
      JSON.stringify({
        privateHandoff: true,
        columns: files.length,
        nodes: parsed.nodeCount,
        bodyLines: directLines,
        bytes: files.reduce((sum, file) => sum + file.bytes.length, 0),
        manifest: 'constructed in memory; no private files written',
        utf16Evidence: 'validated',
      })
    );
  }
);
