import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { parseRuleBook, type RuleUpload } from '../src/domain/ruleImport.js';
import type { RuleBookManifest } from '../src/domain/rules.js';
function fixture(body: string, enrichment?: RuleBookManifest['enrichment']): RuleUpload[] {
  const bytes = Buffer.from(body);
  const manifest: RuleBookManifest = {
    format: 'rules-book',
    source: { slug: 'example-core', title: 'Original synthetic book', pageCount: 3, pdfHash: null },
    columns: [
      {
        column: 'core_rules',
        file: 'core_rules.md',
        hash: createHash('sha256').update(bytes).digest('hex'),
      },
    ],
    converter: { id: 'synthetic-fixture', version: '1' },
    markerFormatVersion: 1,
    coverage: { description: 'Original synthetic fixture only', omissions: [] },
    ...(enrichment ? { enrichment } : {}),
  };
  return [
    { name: 'manifest.json', bytes: Buffer.from(JSON.stringify(manifest)) },
    { name: 'core_rules.md', bytes },
  ];
}
const header = '<!-- column: core_rules | source: example-core -->\n';

test('observed splitter-v1 headings before markers are node metadata, fixed generator headers and unknown printed-page markers import deterministically', () => {
  const result = parseRuleBook(
    fixture(
      '<!-- column: core_rules | source: example-core | generated by split_by_outline.py from the outline; do not edit by hand -->\n\n# Original structural parent\n<!-- node: parent | pages: - | printed: - -->\n\n## Original child\n<!-- node: parent.child | pages: 1-2 | printed: - -->\n\n<!-- page 1 -->\nOriginal 🐉 body.\n<!-- page 2 (printed 1) -->\nSecond original body.\n'
    )
  );
  const parent = result.columns.core_rules['example-core']!.children.parent!;
  const child = parent.children.child!;
  assert.equal(parent.name, 'Original structural parent');
  assert.equal(parent.text, '');
  assert.equal(parent.structural, true);
  assert.equal(child.name, 'Original child');
  assert.equal(child.text, '\nOriginal 🐉 body.\nSecond original body.\n');
  assert.equal(child.pageSpans![0]!.start, 1);
  assert.equal(child.pageSpans![0]!.printedPage, null);
  assert.equal(child.pageSpans![1]!.pdfPage, 2);
  assert.equal(child.text.slice(child.pageSpans![1]!.start), 'Second original body.\n');
});
test('annotated import assigns every original span once, preserving tables, Unicode and fenced markers', () => {
  const result = parseRuleBook(
    fixture(
      header +
        '<!-- node: checks | pages: - | printed: - -->\n' +
        '<!-- node: checks.sneak | pages: 1-3 | printed: 5-7 -->\n' +
        '# Sneak\n<!-- page 1 (printed 5) -->\n' +
        'Alpha 🐉\n| d6 | result |\n| 6 | success |\n' +
        '<!-- page 3 (printed 7) -->\nBeta\n' +
        '```md\n<!-- node: fake | pages: 1 | printed: 1 -->\n```\n'
    )
  );
  assert.equal(result.nodeCount, 2);
  const parent = result.columns.core_rules['example-core']!.children.checks!;
  const child = parent.children.sneak!;
  assert.equal(parent.structural, true);
  assert.equal(parent.text, '');
  assert.deepEqual(parent.pdfPages, []);
  assert.equal(child.name, 'Sneak');
  assert.match(child.text, /🐉\n\| d6 \| result \|/);
  assert.match(child.text, /<!-- node: fake/);
  assert.deepEqual(child.pdfPages, [1, 2, 3]);
  assert.equal(child.pageSpans![0]!.start, '# Sneak\n'.length);
  assert.equal(
    child.text.slice(child.pageSpans![1]!.start, child.pageSpans![1]!.end).startsWith('Beta'),
    true
  );
  assert.equal(child.pageSpans![1]!.pdfPage, 3);
});
test('hashes are checked on uploaded bytes; canonical text normalizes LF before offset evidence', () => {
  const result = parseRuleBook(
    fixture(
      header.replaceAll('\n', '\r\n') +
        '<!-- node: check | pages: 1 | printed: - -->\r\n🐉 test\r\n',
      {
        'core_rules.check': {
          fields: { symbol: 'dragon' },
          fieldEvidence: { symbol: { kind: 'text', quote: '🐉', start: 0, end: 2 } },
        },
      }
    )
  );
  assert.equal(result.columns.core_rules['example-core']!.children.check!.text, '🐉 test\n');
  const corrupted = fixture(header + '<!-- node: check | pages: 1 | printed: - -->\nText');
  corrupted[1]!.bytes = Buffer.from('changed');
  assert.throws(() => parseRuleBook(corrupted), /hash mismatch/);
});
test('unsafe/duplicate/missing files, absent parents, body gaps, invalid pages and unknown enrichment fail with locations', () => {
  for (const body of [
    header + '<!-- node: absent.child | pages: 1 | printed: - -->\nText',
    header + 'Unassigned prose\n',
    header + '<!-- node: check | pages: 4 | printed: - -->\nText',
    header +
      '<!-- node: check | pages: 1 | printed: - -->\nText\n<!-- node: check | pages: 1 | printed: - -->\n',
    header + '<!-- node: constructor | pages: 1 | printed: - -->\nText',
    '<!-- column: lore | source: example-core -->\n',
  ])
    assert.throws(() => parseRuleBook(fixture(body)), /core_rules.md:\d+:/);
  const files = fixture(header + '<!-- node: check | pages: 1 | printed: - -->\nText');
  assert.throws(() => parseRuleBook([...files, files[1]!]), /duplicate/);
  assert.throws(() => parseRuleBook([files[0]!]), /exactly/);
  assert.throws(
    () =>
      parseRuleBook(
        fixture(header + '<!-- node: check | pages: 1 | printed: - -->\nText', {
          'core_rules.unknown': { summary: 'Derived' },
        })
      ),
    /Enrichment path/
  );
});
test('strict UTF-8 rejects malformed byte sequences even when their hashes match', () => {
  const files = fixture(header);
  files[0]!.bytes = Buffer.from([0xff]);
  assert.throws(() => parseRuleBook(files), /Invalid UTF-8/);
});
test('a manifest prepared by an older app is rejected with regeneration guidance', () => {
  const [manifest, column] = fixture(header + '<!-- node: a | pages: - | printed: - -->\nText\n');
  const old = { ...JSON.parse(manifest!.bytes.toString()), version: 1 };
  assert.throws(
    () =>
      parseRuleBook([{ name: 'manifest.json', bytes: Buffer.from(JSON.stringify(old)) }, column!]),
    /older app; regenerate it with npm run rules:manifest/
  );
});
